<?php
namespace gamboamartin\empleado\models;
use base\orm\_modelo_parent;


use gamboamartin\errores\errores;
use PDO;
use stdClass;

class em_clase_riesgo extends _modelo_parent{

    public function __construct(PDO $link){
        $tabla = 'em_clase_riesgo';
        $columnas = array($tabla=>false);
        $campos_obligatorios = array('descripcion','codigo','descripcion_select','alias','codigo_bis','factor');

        $campos_view['codigo'] = array('type' => 'inputs');
        $campos_view['descripcion'] = array('type' => 'inputs');
        $campos_view['factor']['type'] = array('type' => 'inputs');


        parent::__construct(link: $link,tabla:  $tabla, campos_obligatorios: $campos_obligatorios,
            columnas: $columnas,campos_view: $campos_view);

        $this->NAMESPACE = __NAMESPACE__;
    }

    public function alta_bd(array $keys_integra_ds = array('descripcion', 'factor')): array|stdClass
    {

        if(!isset($this->registro['codigo'])){
            $codigo = $this->registro['descripcion'].' '.$this->registro['factor'];
            $this->registro['codigo'] = $codigo;
        }

        $r_alta_bd = parent::alta_bd(keys_integra_ds: $keys_integra_ds); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al insertar clase_riesgo',data:  $r_alta_bd);
        }
        return $r_alta_bd;

    }


}