<?php
namespace gamboamartin\empleado\models;
use base\orm\modelo;
use gamboamartin\errores\errores;
use models\bn_sucursal;
use PDO;
use stdClass;


class em_cuenta_bancaria extends modelo{

    public function __construct(PDO $link){
        $tabla = 'em_cuenta_bancaria';
        $columnas = array($tabla=>false, 'em_empleado'=>$tabla,'bn_sucursal'=>$tabla,'bn_banco'=>'bn_sucursal');
        $campos_obligatorios = array('bn_sucursal_id','em_empleado_id','descripcion_select');
        $campos_view = array('bn_sucursal_id' => array('type' => 'selects', 'model' => new bn_sucursal($link)),
            'em_empleado_id' => array('type' => 'selects', 'model' => new em_empleado($link)),
            'fecha' => array('type' => 'dates'));
        parent::__construct(link: $link,tabla:  $tabla, campos_obligatorios: $campos_obligatorios,
            columnas: $columnas,campos_view: $campos_view);
    }

    public function alta_bd(): array|stdClass
    {

        if(!isset($this->registro['descripcion_select']) ||$this->registro['descripcion_select'] === ''){
            $this->registro['descripcion_select'] = strtoupper($this->registro['descripcion']);
        }

        $r_alta_bd = parent::alta_bd(); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al dar de alta cuenta', data: $r_alta_bd);
        }
        return $r_alta_bd;
    }


}