<?php
namespace gamboamartin\empleado\models;
use base\orm\modelo;
use gamboamartin\errores\errores;
use models\im_registro_patronal;
use models\cat_sat_regimen_fiscal;
use models\dp_calle_pertenece;
use models\org_puesto;
use PDO;
use stdClass;

class em_empleado extends modelo{

    public function __construct(PDO $link){
        $tabla = 'em_empleado';
        $columnas = array($tabla=>false, 'im_registro_patronal'=>$tabla, 'cat_sat_regimen_fiscal'=>$tabla,
            'dp_calle_pertenece'=>$tabla);
        $campos_obligatorios = array('nombre','descripcion','codigo','descripcion_select','alias','codigo_bis');
        $campos_view = array(
            'dp_calle_pertenece_id' => array('type' => 'selects', 'model' => new dp_calle_pertenece($link)),
            'cat_sat_regimen_fiscal_id' => array('type' => 'selects', 'model' => new cat_sat_regimen_fiscal($link)),
            'im_registro_patronal_id' => array('type' => 'selects', 'model' => new im_registro_patronal($link)),
            'org_puesto_id' => array('type' => 'selects', 'model' => new org_puesto($link)),
            'fecha' => array('type' => 'dates'));

        parent::__construct(link: $link,tabla:  $tabla, campos_obligatorios: $campos_obligatorios,
            columnas: $columnas,campos_view: $campos_view);
    }

    public function alta_bd(): array|stdClass
    {
        $registro = $this->registro;
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al inicializar registro',data: $registro);
        }

        $keys = array('nombre','ap');
        $valida = $this->validacion->valida_existencia_keys(keys: $keys, registro: $registro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al validar registro',data: $valida);
        }

        if(!isset($registro['am'])){
            $registro['am'] = '';
        }

        if (!isset($registro['descripcion'])) {
            $registro['descripcion'] = $registro['nombre'].' '.$registro['ap'].' ';
            $registro['descripcion'] .= $registro['am'];
        }

        $this->registro['descripcion'] = $registro['descripcion'];

        if(!isset($registro['alias'])){
            $registro['alias'] = $registro['descripcion'];
        }

        $this->registro['alias'] = $registro['alias'];

        if (!isset($registro['descripcion_select'])) {
            $registro['descripcion_select'] = $registro['nombre'].' '.$registro['ap'].' ';
            $registro['descripcion_select'] .= $registro['am'];
        }

        $this->registro['descripcion_select'] = $registro['descripcion_select'];

        if (!isset($registro['codigo_bis'])) {
            $registro['codigo_bis'] = $registro['codigo'];
        }

        $this->registro['codigo_bis'] = $registro['codigo_bis'];

        $r_alta_bd = parent::alta_bd(); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al dar de alta empleado',data: $r_alta_bd);
        }

        return $r_alta_bd;

    }

    public function modifica_bd(array $registro, int $id, bool $reactiva = false): array|stdClass
    {
        if(isset($registro['codigo'])){
            $registro['codigo_bis'] = $registro['codigo'];
        }

        if(isset($registro['nombre']) && isset($registro['ap']) && isset($registro['am']) && isset($registro['rfc'])) {
            $registro['descripcion_select'] = $registro['nombre'] . ' ' . $registro['ap'] . ' ';
            $registro['descripcion_select'] .= $registro['am'] . ' ' . $registro['rfc'];

            $registro['descripcion'] = $registro['nombre'] . ' ' . $registro['ap'] . ' ';
            $registro['descripcion'] .= $registro['am'] . ' ' . $registro['rfc'];

            $registro['alias'] = $registro['descripcion'];
        }
        $r_modifica_bd = parent::modifica_bd($registro, $id, $reactiva); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al modificar empleado',data: $r_modifica_bd);
        }

        return $r_modifica_bd;

    }

    /**
     * Obtiene empresa a partir de empleado
     * @param int $em_empleado_id Identificador del empleado a revisar su empresa
     * @return array|stdClass
     * @version
     */
    public function get_empresa(int $em_empleado_id){
        $r_empleado = $this->registro(registro_id: $em_empleado_id);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener empleado',data: $r_empleado);
        }

        $r_registro_patronal =  (new im_registro_patronal($this->link))->registro(registro_id:
            $r_empleado['im_registro_patronal_id']);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener registro patronal',data: $r_registro_patronal);
        }

        return $r_registro_patronal;
    }
}