<?php

namespace gamboamartin\empleado\models;

use base\orm\modelo;

use gamboamartin\errores\errores;
use PDO;
use stdClass;

class em_tipo_anticipo extends modelo
{

    public function __construct(PDO $link)
    {
        $tabla = 'em_tipo_anticipo';
        $columnas = array($tabla => false);
        $campos_obligatorios = array('descripcion');

        $campos_view['codigo'] = array('type' => 'inputs');
        $campos_view['descripcion'] = array('type' => 'inputs');

        parent::__construct(link: $link, tabla: $tabla, campos_obligatorios: $campos_obligatorios,
            columnas: $columnas, campos_view: $campos_view);

        $this->NAMESPACE = __NAMESPACE__;
    }

    public function alta_bd(): array|\stdClass
    {
        if (!isset($this->registro['descripcion_select'])) {
            $this->registro['descripcion_select'] = $this->registro['descripcion'];
        }

        if (!isset($this->registro['codigo_bis'])) {
            $this->registro['codigo_bis'] = $this->registro['codigo'];
        }

        if (!isset($this->registro['alias'])) {
            $this->registro['alias'] = $this->registro['codigo'];
            $this->registro['alias'] .= $this->registro['descripcion'];
        }

        $r_alta_bd = parent::alta_bd();
        if (errores::$error) {
            return $this->error->error(mensaje: 'Error al dar de alta tipo anticipo', data: $r_alta_bd);
        }

        return $r_alta_bd;
    }

    public function get_tipo_anticipos(int $em_empleado_id): array|stdClass
    {

        $extra_join["em_anticipo"]["key"] = "em_tipo_anticipo_id";
        $extra_join["em_anticipo"]["enlace"] = "em_tipo_anticipo";
        $extra_join["em_anticipo"]["key_enlace"] = "id";
        $extra_join["em_anticipo"]["renombre"] = "em_anticipo";

        $filtro['em_anticipo.em_empleado_id'] = $em_empleado_id;
        $group_by = array('em_tipo_anticipo.id');

        $em_tipo_anticipo = (new em_tipo_anticipo($this->link))->filtro_and(extra_join: $extra_join, filtro: $filtro,
            group_by: $group_by);
        if (errores::$error) {
            return $this->error->error(mensaje: 'Error al obtener los tipos de anticipos del empleado', data: $em_tipo_anticipo);
        }

        return $em_tipo_anticipo;
    }

    public function modifica_bd(array $registro, int $id, bool $reactiva = false): array|\stdClass
    {
        if (!isset($registro['descripcion_select'])) {
            $registro['descripcion_select'] = $registro['descripcion'];
        }

        if (!isset($registro['codigo_bis'])) {
            $registro['codigo_bis'] = $registro['codigo'];
        }

        if (!isset($registro['alias'])) {
            $registro['alias'] = $registro['codigo'];
            $registro['alias'] .= $registro['descripcion'];
        }

        $r_modifica_bd = parent::modifica_bd($registro, $id, $reactiva); // TODO: Change the autogenerated stub
        if (errores::$error) {
            return $this->error->error(mensaje: 'Error al modificar tipo anticipo', data: $r_modifica_bd);
        }

        return $r_modifica_bd;
    }
}