<?php
namespace gamboamartin\empleado\models;
use base\orm\modelo;

use gamboamartin\errores\errores;
use PDO;

class em_tipo_anticipo extends modelo{

    public function __construct(PDO $link){
        $tabla = 'em_tipo_anticipo';
        $columnas = array($tabla=>false);
        $campos_obligatorios = array('descripcion');

        $campos_view['codigo'] = array('type' => 'inputs');
        $campos_view['descripcion'] = array('type' => 'inputs');

        parent::__construct(link: $link,tabla:  $tabla, campos_obligatorios: $campos_obligatorios,
            columnas: $columnas, campos_view: $campos_view);

        $this->NAMESPACE = __NAMESPACE__;
    }

    public function alta_bd(): array|\stdClass
    {
        if (!isset($this->registro['descripcion_select'])) {
            $this->registro['descripcion_select'] = $this->registro['descripcion'];
        }

        if (!isset($this->registro['codigo_bis'])) {
            $this->registro['codigo_bis'] = $this->registro['codigo'];
        }

        if (!isset($this->registro['alias'])) {
            $this->registro['alias'] = $this->registro['codigo'];
            $this->registro['alias'] .= $this->registro['descripcion'];
        }

        $r_alta_bd = parent::alta_bd();
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al dar de alta tipo anticipo',data: $r_alta_bd);
        }

        return $r_alta_bd;
    }

    public function modifica_bd(array $registro, int $id, bool $reactiva = false): array|\stdClass
    {
        if (!isset($registro['descripcion_select'])) {
            $registro['descripcion_select'] = $registro['descripcion'];
        }

        if (!isset($registro['codigo_bis'])) {
            $registro['codigo_bis'] = $registro['codigo'];
        }

        if (!isset($registro['alias'])) {
            $registro['alias'] = $registro['codigo'];
            $registro['alias'] .= $registro['descripcion'];
        }

        $r_modifica_bd = parent::modifica_bd($registro, $id, $reactiva); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al modificar tipo anticipo',data: $r_modifica_bd);
        }

        return $r_modifica_bd;
    }
}