<?php
/**
 * @author Martin Gamboa Vazquez
 * @version 1.0.0
 * @created 2022-05-14
 * @final En proceso
 *
 */

namespace gamboamartin\empleado\controllers;

use gamboamartin\empleado\models\em_clase_riesgo;
use gamboamartin\errores\errores;
use gamboamartin\system\_ctl_base;
use gamboamartin\system\html_controler;
use gamboamartin\system\links_menu;
use gamboamartin\template\html;
use gamboamartin\template_1\directivas;
use html\em_centro_clase_riesgo_html;
use PDO;
use stdClass;

class controlador_em_clase_riesgo extends _ctl_base
{
    private html_controler $html_local;
    public function __construct(PDO      $link, html $html = new \gamboamartin\template_1\html(),
                                stdClass $paths_conf = new stdClass())
    {
        $modelo = new em_clase_riesgo(link: $link);
        $html_ = new em_centro_clase_riesgo_html(html: $html);
        $this->html_local = $html_;
        $obj_link = new links_menu(link: $link, registro_id: $this->registro_id);

        $datatables = new stdClass();
        $datatables->columns = array();
        $datatables->columns['em_clase_riesgo_id']['titulo'] = 'Id';
        $datatables->columns['em_clase_riesgo_descripcion']['titulo'] = 'Clase';
        $datatables->columns['em_clase_riesgo_factor']['titulo'] = 'Factor';

        $datatables->filtro = array();
        $datatables->filtro[] = 'em_clase_riesgo.id';
        $datatables->filtro[] = 'em_clase_riesgo.descripcion';
        $datatables->filtro[] = 'em_clase_riesgo.factor';


        parent::__construct(html: $html_, link: $link, modelo: $modelo, obj_link: $obj_link, datatables: $datatables,
            paths_conf: $paths_conf);


        $this->lista_get_data = true;
    }

    public function alta(bool $header, bool $ws = false): array|string
    {
        $r_alta =  parent::alta(header: false); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al generar template',data:  $r_alta,header:  $header,ws:  $ws);
        }

        $factor = $this->html_local->input_monto(cols: 12, row_upd: new stdClass(),value_vacio: false,
            name: 'factor', place_holder: 'Factor');
        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al generar input',data:  $factor,header:  $header,ws:  $ws);
        }

        $this->inputs->factor = $factor;

        return $r_alta;
    }

    public function modifica(bool $header, bool $ws = false): array|stdClass
    {
        $r_modifica = parent::modifica($header, $ws); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al generar template',data:  $r_modifica,header:  $header,ws:  $ws);
        }

        $factor = $this->html_local->input_monto(cols: 12, row_upd: $this->row_upd,value_vacio: false,
            name: 'factor', place_holder: 'Factor', value: $this->row_upd->factor);
        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al generar input',data:  $factor,header:  $header,ws:  $ws);
        }

        $this->inputs->factor = $factor;
        return $r_modifica;
    }


}
